Add support for setting metadata and user agent
grpc-ecosystem/polyglot pull request #50
Opened 2017-04-26 16:08 UTC by marcwilson-g

Should satisfy https://github.com/grpc-ecosystem/polyglot/issues/42

2017-04-27 09:14 UTC, dinowernli requested changes
Thanks for the contribution, the change looks really nice. Just a few nits here and there, then we should be good.

2017-04-27 09:14 UTC, dinowernli commented on src/main/java/me/dinowernli/grpc/polyglot/config/CommandLineArgs.java
> +  @Option(name = "--metadata", metaVar = "<key>,<value>,<key>,<value>,...")
Can we make this k1:v1,k2:v2,...?

2017-04-27 09:14 UTC, dinowernli commented on src/main/java/me/dinowernli/grpc/polyglot/config/CommandLineArgs.java
> +	  return Optional.empty();
nit: indentation looks off

2017-04-27 09:14 UTC, dinowernli commented on src/main/java/me/dinowernli/grpc/polyglot/config/CommandLineArgs.java
> +    if (parts.size() % 2 != 0) {
Preconditions.checkArgument?

2017-04-27 09:14 UTC, dinowernli commented on src/main/java/me/dinowernli/grpc/polyglot/config/CommandLineArgs.java
> +  public Optional<Multimap<String, String>> metadata() {
Please make this one of the guava immutable multimaps (so that all returned fields here stay immutable)

2017-09-29 15:20 UTC, marcwilson-g commented
Sorry, I completely dropped the ball on this. I missed the notification for your comments and never circled back and a lot of time has passed.
I saw someone picked it up in https://github.com/grpc-ecosystem/polyglot/pull/71, so I'm happy to drop this in favour of that one, in order to get it in

2017-09-29 16:36 UTC, dinowernli commented
@marcwilson-g well, it's your change :) if you're planning on fixing this up, I'll wait. If not, we can merge the copy. Up to you.

2017-10-02 13:16 UTC, marcwilson-g commented
Happy for you to merge the copy, that way it gets in now rather than me intending to get to it and failing for another 3 months..!

2017-10-02 13:16 UTC, closed without merging

2017-10-03 17:06 UTC, nykolaslima commented
Hi @marcwilson-g ,

Thank you for being so nice about it. I did the changes that @dinowernli requested in the copy PR and hope it get merged soon.

Thanks again.