Add GRPC Metadata support
grpc-ecosystem/polyglot pull request #71
Opened 2017-09-27 17:21 UTC by nykolaslima

Add new polyglot command line argument `--metadata` that allow uses to
pass key:value entries that will be configured into GRPC Metadata
headers.

```sh
java -jar polyglot.jar --command=call --metadata=k1:v1,k2:v2 (...)
```

This fixes #42 and was made based on unmerged PR #50

2017-10-02 13:51 UTC, dinowernli requested changes
Thanks a lot for your contribution, just a few small things here and there and we should be good to go.

2017-10-02 13:51 UTC, dinowernli commented on src/main/java/me/dinowernli/grpc/polyglot/grpc/ChannelFactory.java
> + * Knows how to construct grpc channels.
why this change?

2017-10-02 13:51 UTC, dinowernli commented on src/main/java/me/dinowernli/grpc/polyglot/config/ConfigurationLoader.java
> +                .setName(keyValue.getKey())
Indentation looks off (2 spaces per indent, 4 spaces for broken lines). Please fix throughout the PR

2017-10-02 13:51 UTC, dinowernli commented on src/test/java/me/dinowernli/grpc/polyglot/config/ConfigurationLoaderTest.java
> +    ImmutableMultimap<String, String> metadata = new ImmutableMultimap.Builder<String, String>()
ImmutableMultimap.of("key1", "value1", "key2", "value2")?

2017-10-02 13:51 UTC, dinowernli commented on src/test/java/me/dinowernli/grpc/polyglot/config/CommandLineArgsTest.java
> +            .putAll("key1", "value1", "value2")
ImmutableMultimap.of

2017-10-03 17:05 UTC, nykolaslima commented
@dinowernli Thank you for the feedback. I did the requested changes, could you take another look please?

2017-10-05 12:35 UTC, dinowernli approved these changes

2017-10-05 12:36 UTC, dinowernli commented
LGTM, thanks

2017-10-05 12:36 UTC, merged